[ ] //	**************************************************************************************************** //
[ ]
[ ] //	File Name			:	SILKGEN_UseFiles.inc
[ ]
[ ] //	**************************************************************************************************** //
[ ] // 	SILKGEN -				:	All .inc that are specific to SILKGEN Framework are incluced here
[ ] // 	Developer(s)		: 	Amiya Pattnayak
[ ] //	Setup Requirements	: 	NA
[ ]
[+] // 	Revision History
	[ ] //		MM/DD/YY	Creater/Modifier
	[ ] //		12/01/08	Amiya Pattnayak	Created
	[ ] //
[ ] //	**************************************************************************************************** //
[ ]
[ ]
[ ] //Below files are specifice to framework.
[ ] use "SILKGEN_Types.inc"
[ ] use "SILKGEN_Globals.inc"
[ ] use "SILKGEN_WindowsDecl.inc"
[ ] use "SILKGEN_Functions.inc"
[ ] use "SILKGEN_Defaults.inc"
[ ] use "SILKGEN_DriverFunc.inc"
[ ] use "SILKGEN_BrowserDecl.inc"
[ ]
[ ]
[ ] //Reusable functions are available in the below reference .inc file.
[ ] use "SILKGEN_MainFunction.inc"
[ ] use "SILKGEN_BrowserFunc.inc"
[ ] use "SILKGEN_SystemCallsFunc.inc"
[ ] use "SILKGEN_DateTimeFunc.inc"
[ ] use "SILKGEN_WindowInfoFunc.inc"
[ ] use "SILKGEN_ErrorSnapShotFunc.inc"
[ ] use "SILKGEN_DataTypeManipuFunc.inc"
[ ] use "SILKGEN_DataBaseFunc.inc"
[ ] use "SILKGEN_StringManipuFunc.inc"
[ ] use "SILKGEN_MiscellaneousFunc.inc"
[ ] use "SILKGEN_DistributedProcessing.inc"
[ ]
[ ] //use "SILKGEN_Temp.inc"	//Temp file, needs to be removed
[ ]
[ ]
[ ] //project specific use file, which has the reference of all project related .inc files
[ ] use "{PROJECT_HOME}\SilkTest\Includes\Project_UseFiles.inc"
[ ]
[ ]
